Use master
GO
If DB_ID('QLQuanAn') IS NOT NULL
Begin;
	Drop Database QLQuanAn;
End;
GO
Create Database QLQuanAn
Go
Use QLQuanAn
Go

CREATE TABLE DANHMUC
(
	MADM CHAR (10) NOT NULL,
	TENDM NVARCHAR (20),
	GHICHU NVARCHAR (50),
	PRIMARY KEY (MADM)
)

CREATE TABLE MONAN
(
	MAMA CHAR (10) NOT NULL,
	TENMA NVARCHAR (20),
	MADM CHAR (10),
	DONVI NCHAR (10),
	GIABAN INT,
	GIAVON INT,
	PRIMARY KEY (MAMA)
)

CREATE TABLE CHINHANH
(
	MACN CHAR (10) NOT NULL,
	TENCN NVARCHAR (30),
	MABAN CHAR (10),
	MADM CHAR (10),
	MAMA CHAR (10),
	THONGTINCHITIET NVARCHAR (100),
	PRIMARY KEY (MACN)
)

CREATE TABLE BAN
(
	MABAN CHAR (10) NOT NULL,
	SOLUONG INT,
	MAKH CHAR (10),
	THOIGIANDAT DATETIME,
	TINHTRANG CHAR (10),
	MACN CHAR (10),
	PRIMARY KEY (MABAN)
)

CREATE TABLE KHACHHANG
(
	MAKH CHAR (10) NOT NULL,
	TENKH NVARCHAR (20),
	SODIENTHOAI INT,
	DIACHI NVARCHAR (50),
	GHICHU NVARCHAR (50),
	PRIMARY KEY (MAKH)
)

CREATE TABLE NHANVIEN
(
	MANV CHAR (10) NOT NULL,
	TENNV NVARCHAR (20),
	SODIENTHOAI INT,
	DIACHI NVARCHAR (50),
	CHUCVU NVARCHAR (50),
	GHICHU NVARCHAR (20),
	PRIMARY KEY (MANV)
)

CREATE TABLE DONHANG
(
	MADH CHAR (10) NOT NULL,
	LOAIDH NVARCHAR (20),
	MAKH CHAR (10),
	MANV CHAR (10),
	NGAYTAO DATETIME,
	DONGIA INT,
	TRANGTHAI NCHAR (20),
	PRIMARY KEY (MADH)
)

CREATE TABLE CHITIETDONHANG
(
	MADH CHAR (10) NOT NULL,
	MACN CHAR (10) NOT NULL,
	MAKH CHAR (10) NOT NULL,
	MANV CHAR (10) NOT NULL,
	MACP CHAR (10) NOT NULL,
	NGAYTAO DATETIME,
	DONGIA INT,
	TRANGTHAI NCHAR (20),
	PRIMARY KEY (MADH, MACN, MAKH, MANV, MACP)
)

CREATE TABLE CHIPHI
(
	MACP CHAR (10) NOT NULL,
	NGAYTAO DATETIME,
	LOAI NCHAR (10),
	MANV CHAR (10),
	DONGIA INT,
	GHICHU NVARCHAR (20),
	PRIMARY KEY (MACP)
)

CREATE TABLE TAIKHOAN
(
	USERNAME NCHAR (20) NOT NULL,
	PASSWORDS NCHAR (20) NOT NULL,
	MANV CHAR (10),
	CHUCVU NVARCHAR (10),
	NGAYTAO DATETIME,
	NGAYKETTHUC DATETIME,
	GHICHU NVARCHAR (20),
	PRIMARY KEY (USERNAME, PASSWORDS)
)

CREATE TABLE BAOCAO
(
	MABAOCAO CHAR (10) NOT NULL,
	MANV CHAR (10),
	MACN CHAR (10),
	MAKH CHAR (10),
	DOANHTHU INT,
	TUNGAY DATETIME,
	DENNGAY DATETIME,
	PRIMARY KEY (MABAOCAO)
)

ALTER TABLE MONAN 
ADD CONSTRAINT FK_MONAN_DANHMUC
FOREIGN KEY(MADM) REFERENCES DANHMUC(MADM)

ALTER TABLE CHINHANH 
ADD CONSTRAINT FK_CHINHANH_DANHMUC
FOREIGN KEY(MADM) REFERENCES DANHMUC(MADM)

ALTER TABLE CHINHANH 
ADD CONSTRAINT FK_CHINHANH_MONAN
FOREIGN KEY(MAMA) REFERENCES MONAN(MAMA)

ALTER TABLE CHINHANH 
ADD CONSTRAINT FK_CHINHANH_BAN
FOREIGN KEY(MABAN) REFERENCES BAN(MABAN)

ALTER TABLE BAN 
ADD CONSTRAINT FK_BAN_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE BAN 
ADD CONSTRAINT FK_BAN_CHINHANH
FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)

ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_DONHANG
FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)

ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_CHINHANH
FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)

ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_CHIPHI
FOREIGN KEY(MACP) REFERENCES CHIPHI(MACP)

ALTER TABLE CHIPHI
ADD CONSTRAINT FK_CHIPHI_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE BAOCAO
ADD CONSTRAINT FK_BAOCAO_CHINHANH
FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)

ALTER TABLE BAOCAO
ADD CONSTRAINT FK_BAOCAO_KHACHHANG
FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE BAOCAO
ADD CONSTRAINT FK_BAOCAO_NHANVIEN
FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)